root: true
extends:
  - remcohaszing
rules:
  no-invalid-this: off
  no-proto: off
  import/no-extraneous-dependencies: off
  jsdoc/check-tag-names: off
  jsdoc/check-indentation: off
  jsdoc/no-undefined-types: off
